insert into users (user_name, user_city) values ('Brooks', 'Calubcub Dos');
insert into users (user_name, user_city) values ('Redd', 'Eauripik');
insert into users (user_name, user_city) values ('Deb', 'Houjiagang');
insert into users (user_name, user_city) values ('Des', 'Santiago');
insert into users (user_name, user_city) values ('Teresita', 'Miaogou');
insert into users (user_name, user_city) values ('Faustine', 'Rząśnik');
insert into users (user_name, user_city) values ('Maddie', 'Aengceleng');
insert into users (user_name, user_city) values ('Deana', 'Rędziny');
insert into users (user_name, user_city) values ('Nanette', 'Zargarān');
insert into users (user_name, user_city) values ('Meagan', 'Lökbatan');
insert into users (user_name, user_city) values ('Morganica', 'Wielki Kack');
insert into users (user_name, user_city) values ('Thorny', 'Songshan');
insert into users (user_name, user_city) values ('Jameson', 'Uluarang');
insert into users (user_name, user_city) values ('Shannah', 'Tabonok');
insert into users (user_name, user_city) values ('Ruthann', 'Rodez');
insert into users (user_name, user_city) values ('Beryle', 'Banturkrajan');
insert into users (user_name, user_city) values ('Ileane', 'Corujeira');
insert into users (user_name, user_city) values ('Marika', 'Datian');
insert into users (user_name, user_city) values ('Libbie', 'Sua');
insert into users (user_name, user_city) values ('Shena', 'Sumberejo');
insert into users (user_name, user_city) values ('Delmore', 'Rawannawi Village');
insert into users (user_name, user_city) values ('Kalie', 'Ainaži');
insert into users (user_name, user_city) values ('Nickolas', 'Bến Cầu');
insert into users (user_name, user_city) values ('Gustave', 'Vyshchetarasivka');
insert into users (user_name, user_city) values ('Humfrid', 'Monte Francisco');
insert into users (user_name, user_city) values ('Leesa', 'Ramiriquí');
insert into users (user_name, user_city) values ('Paulo', 'Al Qanāyāt');
insert into users (user_name, user_city) values ('Angelika', 'Buri');
insert into users (user_name, user_city) values ('Kelby', 'Fonteleite');
insert into users (user_name, user_city) values ('Kerk', 'Pobé');
insert into users (user_name, user_city) values ('Lannie', 'Puerto La Cruz');
insert into users (user_name, user_city) values ('Ophelia', 'Dogondoutchi');
insert into users (user_name, user_city) values ('Cleo', 'Langxi');
insert into users (user_name, user_city) values ('Cissy', 'Arboga');
insert into users (user_name, user_city) values ('Caresa', 'Le Mans');
insert into users (user_name, user_city) values ('Tadio', 'Rappang');
insert into users (user_name, user_city) values ('Nil', 'Qimeng');
insert into users (user_name, user_city) values ('Tabb', 'Boston');
insert into users (user_name, user_city) values ('Barth', 'Xiangride');
insert into users (user_name, user_city) values ('Wren', 'Shanling');
insert into users (user_name, user_city) values ('Ole', 'Landvetter');
insert into users (user_name, user_city) values ('Alley', 'Castleknock');
insert into users (user_name, user_city) values ('Grove', 'Neringa');
insert into users (user_name, user_city) values ('Tam', 'Vila Nova');
insert into users (user_name, user_city) values ('Burnaby', 'Dolní Počernice');
insert into users (user_name, user_city) values ('Zara', 'Chattanooga');
insert into users (user_name, user_city) values ('Kendell', 'Ash Shaḩānīyah');
insert into users (user_name, user_city) values ('Marja', 'Embajador Martini');
insert into users (user_name, user_city) values ('Hastings', 'Jiyang');
insert into users (user_name, user_city) values ('Nora', 'Pýli');
insert into users (user_name, user_city) values ('Stacy', 'Hongcheng');
insert into users (user_name, user_city) values ('Ugo', 'Avelar');
insert into users (user_name, user_city) values ('Muffin', 'Zhongcheng');
insert into users (user_name, user_city) values ('Joby', 'Chekmagush');
insert into users (user_name, user_city) values ('Melisande', 'Roliça');
insert into users (user_name, user_city) values ('Dolf', 'Lương Bằng');
insert into users (user_name, user_city) values ('Hans', 'Tyringe');
insert into users (user_name, user_city) values ('Janna', 'Karmah an Nuzul');
insert into users (user_name, user_city) values ('Jonas', 'Chernyakhovsk');
insert into users (user_name, user_city) values ('Kelley', 'Kashiwazaki');
insert into users (user_name, user_city) values ('Marita', 'Bondo');
insert into users (user_name, user_city) values ('Willy', 'Embalse');
insert into users (user_name, user_city) values ('Dorothea', 'Iranduba');
insert into users (user_name, user_city) values ('Craggy', 'Bāft');
insert into users (user_name, user_city) values ('Angy', 'Kalahang');
insert into users (user_name, user_city) values ('Riva', 'Wyszogród');
insert into users (user_name, user_city) values ('Olivie', 'Sabana Grande de Boyá');
insert into users (user_name, user_city) values ('Kippar', 'Rajal Norte');
insert into users (user_name, user_city) values ('Cass', 'Moncada');
insert into users (user_name, user_city) values ('Berta', 'Bungo-Takada-shi');
insert into users (user_name, user_city) values ('Lamont', 'Brušperk');
insert into users (user_name, user_city) values ('Coletta', 'Inderka');
insert into users (user_name, user_city) values ('Guthry', 'Ni’ao');
insert into users (user_name, user_city) values ('Drona', 'Bedayutalang');
insert into users (user_name, user_city) values ('Jacinda', 'Anolaima');
insert into users (user_name, user_city) values ('Meredithe', 'Sulitair');
insert into users (user_name, user_city) values ('Nita', 'El Banco');
insert into users (user_name, user_city) values ('Stevie', 'Łąka Prudnicka');
insert into users (user_name, user_city) values ('Danita', 'Shuangshan');
insert into users (user_name, user_city) values ('Ely', 'Växjö');
insert into users (user_name, user_city) values ('Clerc', 'Arras');
insert into users (user_name, user_city) values ('Harriett', 'Nsok');
insert into users (user_name, user_city) values ('Averil', 'Bizhou');
insert into users (user_name, user_city) values ('Verene', 'Xingpinglu');
insert into users (user_name, user_city) values ('Rickey', 'Cetinje');
insert into users (user_name, user_city) values ('Bogey', 'Salavan');
insert into users (user_name, user_city) values ('Boothe', 'Ábrego');
insert into users (user_name, user_city) values ('Sukey', 'Otwock');
insert into users (user_name, user_city) values ('Consuelo', 'Nyagan');
insert into users (user_name, user_city) values ('Turner', 'Novi Kneževac');
insert into users (user_name, user_city) values ('Noelyn', 'Ponte da Pedra');
insert into users (user_name, user_city) values ('Griffith', 'Chernyshkovskiy');
insert into users (user_name, user_city) values ('Kingston', 'Beizhakou');
insert into users (user_name, user_city) values ('Linc', 'Edosaki');
insert into users (user_name, user_city) values ('Chelsy', 'Ngangguk');
insert into users (user_name, user_city) values ('Gennifer', 'Nyangao');
insert into users (user_name, user_city) values ('Ansel', 'Maji');
insert into users (user_name, user_city) values ('Sebastien', 'Salakuray');
insert into users (user_name, user_city) values ('Tomkin', 'Kināna');
insert into users (user_name, user_city) values ('Felicity', 'Moravská Třebová');